apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  aksapi-scale
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aksapi-deployment
  targetCPUUtilizationPercentage: 50

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  web-scale
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  web-deployment
  targetCPUUtilizationPercentage: 50